"""add updated_at to document

Revision ID: 002_add_updated_at
Revises: 001_initial
Create Date: 2025-11-12 15:11:02.769835

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '002_add_updated_at'
down_revision = '001_initial'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('document', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False))
    op.alter_column('document', 'chunk_count',
               existing_type=sa.INTEGER(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('document', 'status',
               existing_type=sa.VARCHAR(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('document', 'status',
               existing_type=sa.VARCHAR(),
               server_default=sa.text("'uploaded'::character varying"),
               existing_nullable=False)
    op.alter_column('document', 'chunk_count',
               existing_type=sa.INTEGER(),
               server_default=sa.text('0'),
               existing_nullable=False)
    op.drop_column('document', 'updated_at')
    # ### end Alembic commands ###

